### ISSUE TITLE
Is this feedstock still active?

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/gwframes-feedstock#8]
I'm wondering if this feedstock is still active. It seems configured to only build on Python 2.7, which is no longer supported by conda-forge, but is still included in migration graphs .This is the final package to be migrated to GSL 2.7 but the bot can't solve for it because of the Python 2.7 thing.

Can this repo be archived, or should it be updated to support Python 3 builds?

**Comment by duncanmmacleod** [comment]
Ping @conda-forge/gwframes (@moble).

**Comment by moble** [comment]
Well, the underlying package is no longer updated and can't be updated to support python 3.  People are still installing it via conda for reproducibility investigations, but we don't need new builds.  So that should be fine as long as "archiving" means that the old builds will still be around.  Is that right?

**Comment by duncanmmacleod** [comment]
Thanks @moble. Yes, all existing builds will stick around, it's just that this feedstock will go into readonly mode and no new packages will be built.

@conda-forge/core, can someone archive this feedstock? I hope that will mean that this package is ignored by the autotick bot when processing migrations.
